USE [master]
GO

/****** Object:  Database [MultiTenancy]    Script Date: 11/09/2014 07:54:04 ******/
CREATE DATABASE [MultiTenancy] ON  PRIMARY 
( NAME = N'MultiTenancy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLSERVER2K8R2\MSSQL\DATA\MultiTenancy.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MultiTenancy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLSERVER2K8R2\MSSQL\DATA\MultiTenancy_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MultiTenancy] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MultiTenancy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MultiTenancy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MultiTenancy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MultiTenancy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MultiTenancy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MultiTenancy] SET ARITHABORT OFF 
GO

ALTER DATABASE [MultiTenancy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MultiTenancy] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MultiTenancy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MultiTenancy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MultiTenancy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MultiTenancy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MultiTenancy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MultiTenancy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MultiTenancy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MultiTenancy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MultiTenancy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MultiTenancy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MultiTenancy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MultiTenancy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MultiTenancy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MultiTenancy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MultiTenancy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MultiTenancy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MultiTenancy] SET  READ_WRITE 
GO

ALTER DATABASE [MultiTenancy] SET RECOVERY FULL 
GO

ALTER DATABASE [MultiTenancy] SET  MULTI_USER 
GO

ALTER DATABASE [MultiTenancy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MultiTenancy] SET DB_CHAINING OFF 
GO

